spring.application.name=kickbox-tracker

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kickbox_tracker
spring.datasource.username=a.crispino
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/kickbox_tracker